GamePortalMVC/Controllers/DownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace GamePortalMVC.Controllers
{
    public class DownloadController : Controller
    {
        public IActionResult Download()
        {
            return View();
        }
    }
}

GamePortalMVC/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace GamePortalMVC.Controllers
{
    public class NewsController : Controller
    {
        public IActionResult News()
        {
            return View();
        }
    }
}

GamePortalMVC/Views/Shared/_Footer.cshtml
@{

}

        <footer id="footer">
            <div class="footer1">
                <div class="container">
                    <div class="row">

                        <div class="col-md-3 widget">
                            <h3 class="widget-title">Contact</h3>
                            <div class="widget-body">
                                <p>
                                    +55 21 96511-9956<br>
                                    <a href="mailto:#">carlosrbatista1980@gmail.com</a><br>
                                    <br>
                                    Rio de Janeiro - Brasil
                                </p>
                                <p class="simplenav">
                                    <a asp-controller="Home" asp-action="Index">Home</a> |
                                    <a asp-controller="Home" asp-action="Privacy">Privacy</a> |
                                    <!--<a href="sidebar-right.html">Sidebar</a> |-->
                                    <a asp-controller="Download" asp-action="Download">Download</a> |
                                    <b><a asp-controller="Login" asp-action="Register">REGISTER</a></b>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-3 widget">
                            <h3 class="widget-title">Follow me</h3>
                            <div class="widget-body">
                                <p class="follow-me-icons clearfix">
                                    <a href="https://www.linkedin.com/in/carlos-rodrigues-batista-8a367775/"><i class="fab fa-linkedin"></i></a>
                                    <a href="https://github.com/carlosrbatista1980/RappelzWebSite"><i class="fab fa-github"></i></a>
                                    <a href="mailto:carlosrbatista1980@gmail.com"><i class="fab fa-google"></i></a>
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6 widget">
                            <h3 class="widget-title">Widget</h3>
                            <div class="widget-body">
                                <p>
                                    My special thanks to a very special person who makes me follow the path of knowledge and dedication to what we believe and what is the best for us no matter how long it takes, Talita Tassila.
                                </p>
                                <p>
                                    <b>Cheers, hold your mug of ale and lets drink together.</b>
                                </p>
                                <p class="text-left">
                                    Carlos 2020, You can do anything but, keep the credits on metadata or visit <a href="https://www.linkedin.com/in/carlos-rodrigues-batista-8a367775/" rel="designer">LinkedIn</a> and say hello.
                                </p>
                            </div>
                        </div>

                    </div> <!-- /row of widgets -->
                </div>
            </div>
        </footer>


@*
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - RappelzWebSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
    
*@

GamePortalMVC/Views/Shared/_Head.cshtml
@{

}
<!-- Required meta tags-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="template by Sergey Pozhilov (GetTemplate.com)">
<meta name="author" content="Carlos Rodrigues Batista (https://www.linkedin.com/in/carlos-rodrigues-batista-8a367775/)">
<meta name="projectGit" content="Rappelz WebSite (https://github.com/carlosrbatista1980/RappelzWebSite)">

<title>Rappelz WebSite</title>

<link rel="shortcut icon" href="~/images/gt_favicon.png">

<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"> -->

<!--<link rel="stylesheet" href="~/css/bootstrap.min.css">-->
<link rel="stylesheet" href="~/css/bootstrap.css">

<link rel="stylesheet" href="~/css/all.min.css">

<!-- Custom styles for our template -->
<link rel="stylesheet" href="~/css/bootstrap-theme.css" media="screen">
<link rel="stylesheet" href="~/css/main.css">

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
    <script src="assets/js/html5shiv.js"></script>
    <script src="assets/js/respond.min.js"></script>
<![endif]-->

<title>@ViewData["Title"] - RappelzWebSite</title>


@*
<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
</environment>
<link rel="stylesheet" href="~/css/site.css" />

    *@

GamePortalMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @Html.Partial("_Head")
</head>
<body>
<header>
    @Html.Partial("_TopMenu");
</header>
<div class="main" class="pb-3">
    <div class="container" style="min-height: 768px">
        <partial name="_CookieConsentPartial"/>
        <main role="main" >
            @RenderBody()
        </main>
    </div>
</div>

@Html.Partial("_Footer");

@Html.Partial("_ScriptsEndOfPage");
    
@RenderSection("Scripts", required: false)
</body>
</html>

GamePortalMVC/Views/Shared/_ScriptsEndOfPage.cshtml
@using Microsoft.CodeAnalysis
@{
}

@*
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
*@

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"></script> -->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script> -->

<script src="~/js/bootstrap.js"></script>
<script src="~/js/headroom.min.js"></script>
<script src="~/js/jQuery.headroom.min.js"></script>
<script src="~/js/template.js"></script>
<script src="~/js/all.min.js"></script>
<script>
    $("#success-alert").fadeTo(4000, 500).slideUp(500, function(){
        $("#success-alert").slideUp(500);
    });
    $("#error-alert").fadeTo(8000, 500).slideUp(500, function(){
        $("#error-alert").slideUp(500);
    });
</script>


<!-- <link rel="stylesheet" href="~/css/all.min.css"> -->
<!-- <script src="~/js/all.min.js"></script> -->
<!-- Google Maps -->
@*
    <script src="https://maps.googleapis.com/maps/api/js?key=&amp;sensor=false&amp;extension=.js"></script>
    <script src="~/js/google-map.js"></script>
*@




<!-- Main JS-->
<!-- <script src="~/js/formLogin.js"></script>-->

GamePortalMVC/Views/Shared/_SideBar.cshtml
@{

}
<!-- Sidebar -->
<aside class="col-sm-4 sidebar sidebar-right">

    <div class="widget">
        <h4>SIDE BAR TITLE</h4>
        <ul class="list-unstyled list-spaces">
            <li>
                <a href="">Link for contact 1</a><br><span class="small text-muted">place contacts or marketing here</span>
            </li>
            <li>
                <a href="">Link for contact 2</a><br><span class="small text-muted">place contacts or marketing here</span>
            </li>
            <li>
                <a href="">Link for contact 3</a><br><span class="small text-muted">place contacts or marketing here</span>
            </li>
            <li>
                <a href="">Link for contact 4</a><br><span class="small text-muted">place contacts or marketing here</span>
            </li>
            <li>
                <a href="">Link for contact 5</a><br><span class="small text-muted">place contacts or marketing here</span>
            </li>
        </ul>
    </div>

</aside>
<!-- /Sidebar -->

GamePortalMVC/Views/Shared/_TopMenu.cshtml
@using System.Security.Claims;
@using System.Security;

@{

}

<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom">
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <span class="text-left text-secondary" alt="Rappelz WebSite">Rappelz WebSite</span>
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li>
                    <a asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li>
                    <a asp-controller="Download" asp-action="Download">Download</a>
                </li>
                <li>
                    <a asp-controller="News" asp-action="News">News</a>
                </li>

                <!--<li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">More Pages <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="sidebar-left.html">Left Sidebar</a></li>
            <li class="active"><a href="sidebar-right.html">Right Sidebar</a></li>
        </ul>
    </li>
    -->
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <h4>
                                <b>Welcome!, @ViewData.Model.account</b>
                            </h4>
                        </li>
                    }

                    if (ViewData.Model?.SessionId != 0 && ViewData.Model != null)
                    {
                        <li>
                            <h4>
                                <b> vindo!, @ViewData.Model.account</b>
                            </h4>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a asp-controller="Login" asp-action="Login">Login</a>
                        </li>
                    }
                }

                <li>
                    <a class="btn" asp-controller="Login" asp-action="Register">REGISTER</a>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->


@*

    <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">-->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
                <div class="container">
                    @*PAGINA DE CARREGAMENTO PADRÃO
                    <a class="nav-item h4" asp-area="" asp-controller="Home" asp-action="Index">
                        <span class=""><img src="~/img/Initial_logo.jpg" /></span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                        @* DEFAULT
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>


                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item h4">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                    <span class="border border-danger btn btn-primary col-auto">Home</span>
                                </a>
                            </li>
                            <li class="nav-item h4">
                                <a class="nav-link" asp-area="" asp-controller="News" asp-action="News">
                                    <span class="border border-danger btn btn-primary col-auto">News</span>
                                </a>
                            </li>
                            <li class="nav-item h4">
                                <a class="nav-link" asp-area="" asp-controller="Download" asp-action="Download">
                                    <span class="border border-danger btn btn-primary col-auto">Download</span>
                                </a>
                            </li>
                            <li class="nav-item h4">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">
                                    <span class="border border-danger btn btn-primary col-auto">Privacy</span>
                                </a>
                            </li>
                            <li class="nav-item h4">
                                <a class="nav-link" asp-area="" asp-controller="Register" asp-action="Register">
                                    <span class="border border-danger btn btn-primary col-auto">Register</span>
                                </a>
                            </li>
                            <li class="nav-item h4">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Login">
                                    <span class="border border-danger btn btn-primary col-auto">Login</span>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>



*@